###################################

# Run SwiftLint against code base #

###################################

name: Nicolas Riscalas's Professional Linter

on: [push, pull_request]

jobs:

  SwiftLint--strict:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: GitHub Action for SwiftLint with --strict

        uses: norio-nomura/action-swiftlint@3.2.1

        with:

          args: --strict
